export const USER_STATE_CHANGE = "USAER_STATE_CHANGE";
export const USER_POSTS_STATE_CHANGE = "USER_POSTS_STATE_CHANGE";
export const ALL_USERS_POSTS_STATE_CHANGE = "ALL_USERS_POSTS_STATE_CHANGE";
export const ALL_USERS_STATE_CHANGE = "ALL_USERS_STATE_CHANGE";
export const CLEAR_DATA_ON_LOGOUT = "CLEAR_DATA_ON_LOGOUT";
